#!/bin/bash

TS=$(date '+%Y%m%d-%H%M%S')
docker tag $IMAGE_NAME $DOCKER_REPO:${TS}_$DOCKER_TAG
docker push $DOCKER_REPO:${TS}_$DOCKER_TAG

if [[ "$DOCKER_TAG" == "heavy_latest" ]]; then
	docker tag $IMAGE_NAME $DOCKER_REPO:latest
	docker push $DOCKER_REPO:latest
fi

if [[ "$DOCKER_TAG" == "heavy_next" ]]; then
	docker tag $IMAGE_NAME $DOCKER_REPO:next
	docker push $DOCKER_REPO:next
fi
